### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by JVimes** [JohanLarsson/KillWpfDesigner#3]
The extension isn't listed in the marketplace when using Visual Studio 2019 Preview. The final release date is in just over a month, so figured I'd request 2019 support. This might help, [How to upgrade extensions to support Visual Studio 2019](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/). Thanks!

**Comment by JohanLarsson** [comment]
Do you feel like writing a PR with this? I never bothered with installing the VS2019 preview.

**Comment by JVimes** [comment]
I had to target at least .NET 4.6 to get it to build. Then I tweaked the .vsixmanifest per the article, and it would run in the debugger, but didn't kill xdesproc, and there was a warning about the extension using deprecated APIs. The "next steps" section of that article mentions migrating to `AsyncPackage`, and I notice the extension uses non-async `Package`. That's all the time I have for it right now, unfortunately.

**Comment by JohanLarsson** [comment]
Ok, I'll have a look then, thanks for the effort!

**Comment by JohanLarsson** [comment]
Published version 1.1.0 now, hope it works. Please report back if it works on VS2019.
I did not convert to async package, don't think this small extension adds much to load times. Did not feel like tool fighting any more :)

**Comment by JVimes** [comment]
Thank you much. It has the deprecated API warning, but it works.

**Comment by JohanLarsson** [comment]
Published v 1.1.1

**Comment by JVimes** [comment]
Works on my machine. Thanks! :)
